server:
  port: 8080

spring:
  application:
    name: collector
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8081

kafka:
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1 